name: OCI build
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag in the from v0.0.0'
        required: true
        type: string
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # use buildx
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2

      # use quemu
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      # use semver naming strategy
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/krzysztof-winiarczyk/fibcalc
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      # login to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      # login to ghcr.io
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build and push to dockerhub
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=docker.io/kveeen/fibcalc:buildcache
          cache-to: type=registry,ref=docker.io/kveeen/fibcalc:buildcache
          platforms: linux/arm64/v8,linux/amd64
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}